### ISSUE TITLE
Set Reply-To header when sending e-mail contact on behalf of user

### ISSUE THREAD

**Issue by RafDevX** [datasektionen/GinAndTonic#27]
When a user messages a team through the system (i.e., using the [`contact.html`](https://github.com/datasektionen/GinAndTonic/blob/main/templates/emails/contact.html) template), the `Reply-To:` header should be set to the user's e-mail address, allowing the recipient to just press "Reply" on their e-mail client without accidentally e-mailing `tessera-contact@datasektionen.se`.

It seems like the [spam API](https://github.com/datasektionen/spam) supports this easily.

**Comment by DowLucas** [comment]
Great find, thanks!
